# Site Settings
baseurl: ""
url : "http://gksmldia.github.io"
logo: '/public/logo1.png'
locale: ko_KR

# Blog Settings
theme_settings :
  title : Midsummer Night's Honey
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Hanui Shin
    description : 성장하는 것은 살아있다는 것의 증거
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : JAVA
        value : 75  # Percent value
      - skill : Python
        value : 75  # Percent value
      - skill : JS
        value : 90  # Percent value
      - skill : Elastic
        value : 30  # Percent value
        
  # Icons
  icons :
    email:  gksmldia@google.com
    linkedin:  # Full URL 
    github: gksmldia
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
